# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ventana_inicial.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Inicio(object):
    def setupUi(self, Inicio):
        Inicio.setObjectName("Inicio")
        Inicio.resize(488, 243)
        self.centralwidget = QtWidgets.QWidget(Inicio)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 461, 141))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(244, 20, 191, 101))
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(self.groupBox)
        self.widget.setGeometry(QtCore.QRect(70, 20, 171, 101))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Automatico = QtWidgets.QRadioButton(self.widget)
        self.Automatico.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Automatico.setIconSize(QtCore.QSize(30, 30))
        self.Automatico.setObjectName("Automatico")
        self.verticalLayout.addWidget(self.Automatico)
        self.Manual = QtWidgets.QRadioButton(self.widget)
        self.Manual.setIconSize(QtCore.QSize(30, 30))
        self.Manual.setObjectName("Manual")
        self.verticalLayout.addWidget(self.Manual)
        self.Aceptar = QtWidgets.QPushButton(self.centralwidget)
        self.Aceptar.setGeometry(QtCore.QRect(190, 160, 111, 31))
        self.Aceptar.setObjectName("Aceptar")
        Inicio.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Inicio)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 488, 26))
        self.menubar.setObjectName("menubar")
        Inicio.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Inicio)
        self.statusbar.setObjectName("statusbar")
        Inicio.setStatusBar(self.statusbar)

        self.retranslateUi(Inicio)
        QtCore.QMetaObject.connectSlotsByName(Inicio)

    def retranslateUi(self, Inicio):
        _translate = QtCore.QCoreApplication.translate
        Inicio.setWindowTitle(_translate("Inicio", "Ventana de Inicio"))
        self.groupBox.setTitle(_translate("Inicio", "Escoja una opción de desarrollo"))
        self.label.setText(_translate("Inicio", "Seleccione una opción"))
        self.Automatico.setText(_translate("Inicio", "Automático"))
        self.Manual.setText(_translate("Inicio", "Manual"))
        self.Aceptar.setText(_translate("Inicio", "Aceptar"))


''' if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Inicio = QtWidgets.QMainWindow()
    ui = Ui_Inicio()
    ui.setupUi(Inicio)
    Inicio.show()
    sys.exit(app.exec_()) '''
