# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Carga.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Carga(object):
    def setupUi(self, Carga):
        Carga.setObjectName("Carga")
        Carga.resize(632, 413)
        self.centralwidget = QtWidgets.QWidget(Carga)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 10, 621, 131))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(100, 20, 371, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.Abrir = QtWidgets.QPushButton(self.centralwidget)
        self.Abrir.setGeometry(QtCore.QRect(10, 140, 93, 28))
        self.Abrir.setObjectName("Abrir")
        Carga.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Carga)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 632, 26))
        self.menubar.setObjectName("menubar")
        Carga.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Carga)
        self.statusbar.setObjectName("statusbar")
        Carga.setStatusBar(self.statusbar)

        self.retranslateUi(Carga)
        QtCore.QMetaObject.connectSlotsByName(Carga)

    def retranslateUi(self, Carga):
        _translate = QtCore.QCoreApplication.translate
        Carga.setWindowTitle(_translate("Carga", "Carga IP"))
        self.groupBox.setTitle(_translate("Carga", "Estado de la Conexión"))
        self.label.setText(_translate("Carga", "TextLabel"))
        self.Abrir.setText(_translate("Carga", "Abrir Ventana"))
