# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Carga.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Carga(object):
    def setupUi(self, Carga):
        Carga.setObjectName("Carga")
        Carga.resize(632, 154)
        self.centralwidget = QtWidgets.QWidget(Carga)
        self.centralwidget.setObjectName("centralwidget")
        self.Abrir = QtWidgets.QPushButton(self.centralwidget)
        self.Abrir.setGeometry(QtCore.QRect(450, 30, 93, 28))
        self.Abrir.setObjectName("Abrir")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(40, 30, 381, 31))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(270, 70, 121, 31))
        self.label.setObjectName("label")
        Carga.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Carga)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 632, 26))
        self.menubar.setObjectName("menubar")
        Carga.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Carga)
        self.statusbar.setObjectName("statusbar")
        Carga.setStatusBar(self.statusbar)

        self.retranslateUi(Carga)
        QtCore.QMetaObject.connectSlotsByName(Carga)

    def retranslateUi(self, Carga):
        _translate = QtCore.QCoreApplication.translate
        Carga.setWindowTitle(_translate("Carga", "MainWindow"))
        self.Abrir.setText(_translate("Carga", "Abrir Ventana"))
        self.label.setText(_translate("Carga", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Carga = QtWidgets.QMainWindow()
    ui = Ui_Carga()
    ui.setupUi(Carga)
    Carga.show()
    sys.exit(app.exec_())
