# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Carga.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Carga(object):
    def setupUi(self, Carga):
        Carga.setObjectName("Carga")
        Carga.resize(632, 200)
        self.centralwidget = QtWidgets.QWidget(Carga)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(60, 20, 481, 131))
        self.groupBox.setObjectName("groupBox")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.groupBox)
        self.plainTextEdit.setGeometry(QtCore.QRect(50, 40, 381, 31))
        self.plainTextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.Abrir = QtWidgets.QPushButton(self.groupBox)
        self.Abrir.setGeometry(QtCore.QRect(180, 80, 93, 28))
        self.Abrir.setObjectName("Abrir")
        Carga.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Carga)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 632, 26))
        self.menubar.setObjectName("menubar")
        Carga.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Carga)
        self.statusbar.setObjectName("statusbar")
        Carga.setStatusBar(self.statusbar)

        self.retranslateUi(Carga)
        QtCore.QMetaObject.connectSlotsByName(Carga)

    def retranslateUi(self, Carga):
        _translate = QtCore.QCoreApplication.translate
        Carga.setWindowTitle(_translate("Carga", "Carga IP"))
        self.groupBox.setTitle(_translate("Carga", "Escribir la dirección IP del PLC"))
        self.plainTextEdit.setPlaceholderText(_translate("Carga", "Por favor escribir la dirección IP del PLC"))
        self.Abrir.setText(_translate("Carga", "Abrir Ventana"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Carga = QtWidgets.QMainWindow()
    ui = Ui_Carga()
    ui.setupUi(Carga)
    Carga.show()
    sys.exit(app.exec_())
